export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_LISTING_BEGIN = 'CREATE_LISTING_BEGIN'
export const CREATE_LISTING_SUCCESS = 'CREATE_LISTING_SUCCESS'
export const CREATE_LISTING_ERROR = 'CREATE_LISTING_ERROR'

export const GET_LISTING_BEGIN = 'GET_LISTING_BEGIN'
export const GET_LISTING_SUCCESS = 'GET_LISTING_SUCCESS'

export const SET_EDIT_LISTING = 'SET_EDIT_LISTING'

export const DELETE_LISTING_BEGIN = 'DELETE_LISTING_BEGIN'

export const EDIT_LISTING_BEGIN = 'EDIT_LISTING_BEGIN'
export const EDIT_LISTING_SUCCESS = 'EDIT_LISTING_SUCCESS'
export const EDIT_LISTING_ERROR = 'EDIT_LISTING_ERROR'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const CHANGE_PAGE = 'CHANGE_PAGE'

export const GET_USER_BY_ADMIN_BEGAN = 'GET_USER_BY_ADMIN_BEGAN'
export const GET_USER_BY_ADMIN_SUCCESS = 'GET_USER_BY_ADMIN_SUCCESS'
