export const largedata = [
  {
    id: 1,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/webp_5e6b6903-144d-4e0c-9073-59cfd10ad395.png',
    category: 'WEBSITE',
    websitename: 'vozwire.com',
    description:
      'Political news blog generating daily revenue from display ads and much more',
    price: '15000 PKR',
    status: 'sign up / Log in first to view',
    bid: '5',
  },
  {
    id: 2,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/webp_32dd823c-88fb-4530-b758-c4f9faaa2868.JPG',
    category: 'WEBSITE',
    websitename: 'giveaway.com',
    description:
      'Highly Automated - Passive Authority Site - Consistent Income w/ Worldwide...',
    price: '20000 PKR',
    status: 'sign up / Log in first to view',
    bid: '3',
  },
  {
    id: 3,
    img: 'https://d1zazrti94enmy.cloudfront.net/assets/search/placeholders/services-14ff37c2ff335a77c5388ee71940387eb0b4952cc3be4f66143482f6824d0dfd.svg',
    category: 'WEBSITE',
    websitename: 'EnjoyTime.com',
    description:
      'Huge Portal Of Fun, Games, Things To Do To Enjoy Your Time, Making $500/mo...',
    price: '25000 PKR',
    status: 'sign up / Log in first to view',
    bid: '0',
  },
  {
    id: 4,
    img: 'https://d1zazrti94enmy.cloudfront.net/assets/search/placeholders/content-7ca6a9c82f989d2ebb3c782ac750f416e4e2adb662a2035a741d86207268ded2.svg',
    category: 'DOMAIN',
    websitename: 'insurancearms.com',
    description:
      'Brand new offering best guarantee for all insurance based business activities.',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '1',
  },
  {
    id: 5,
    img: 'https://d1zazrti94enmy.cloudfront.net/assets/search/placeholders/services-14ff37c2ff335a77c5388ee71940387eb0b4952cc3be4f66143482f6824d0dfd.svg',
    category: 'PROJECT',
    websitename: 'Jazz Cash And Easy Paisa Integration In Laravel',
    description:
      ' Its a subscription based project so the script should be able to generate...',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '7',
  },
  {
    id: 6,
    img: 'https://d1zazrti94enmy.cloudfront.net/assets/search/placeholders/amazon-d81aef0f24bf323a988a4069928ea5d37ddb50968d42029871fe9f106e54142c.svg',
    category: 'PROJECT',
    websitename: 'Translate A PDF Document',
    description:
      'A translators which can translate a website content into a PDF document.',
    price: '12000 PKR',
    status: 'sign up / Log in first to view',
    bid: '3',
  },
  {
    id: 7,
    img: 'https://d1zazrti94enmy.cloudfront.net/assets/search/placeholders/services-14ff37c2ff335a77c5388ee71940387eb0b4952cc3be4f66143482f6824d0dfd.svg',
    category: 'PROJECT',
    websitename: ' Recognizing patterns',
    description: 'Machine Learning project for recognizing patterns.',
    price: '20000 PKR',
    status: 'sign up / Log in first to view',
    bid: '9',
  },
  {
    id: 8,
    img: 'https://d1zazrti94enmy.cloudfront.net/assets/search/placeholders/ecommerce-10f4c697f0c0d1666468627a72edab6043d55242f2164fd70dc293b1938f4057.svg',
    category: 'PROJECT',
    websitename: 'Calculator in JavaScript',
    description: 'A scientific calculator that is easy to use.',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '10',
  },
  {
    id: 9,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/website_regular_a67fadf6-bddc-446a-90a5-cb9081adeeb6.png',
    category: 'DOMAIN',
    websitename: 'Gohanoline.com',
    description:
      '2 UK Registered semi-AUTOMTED businesses generated $51 (without marketing) + $3500 premium company domains & websites',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '10',
  },
  {
    id: 10,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/c437cd36-1e35-414f-a740-1268e1e6a75e.png',
    category: 'DOMAIN',
    websitename: 'BottleMate',
    description:
      'A decade old online business selling an evergreen product with huge potential. Great mark-up and the potential to expand internationally.',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '12',
  },
  {
    id: 11,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/website_regular_02d2a6d2-c73f-4ad0-8bb8-b61bcf10196d.png',
    category: 'WEBSITE',
    websitename: 'Lostmycarid.com',
    description:
      'Our website was designed to Better help customers in need of an automotive locksmith nation wide with 30 other domains linked to our main website to better cont',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '19',
  },
  {
    id: 12,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/website_regular_652da142-e6c1-4a0d-bcc5-6eb11fe9ab1f.png',
    category: 'OTHER',
    websitename: 'rethink.onl',
    description:
      'Quora like website to share thoughts and knowledge. We have various websites running and many top level domains, needs Funding, to provide fund for our websites mkravi@gmx.com, lansamworld@gmail.com',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '17',
  },
  {
    id: 13,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/9332860e-57f9-459d-b1ca-902014551529.png',
    category: 'iOS App',
    websitename: 'Ecig Media',
    description:
      '9y/o established and profitable Advertising and SEO marketing business with 102 domains and a 43% profit margin, making $8,054 revenue/mo. 94% organic traffic.',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '8',
  },
  {
    id: 14,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/webp_2a72423a-eefd-4028-ac1b-795e29d94f0c.png',
    category: 'OTHER',
    websitename: 'monestor-lyrics.com',
    description:
      'This Website is created to provide the Latest and Old Songs Lyrics. ENG, HINDI, PUNJABI LYRICS DA-16, PA-32 2000+ lyrics already added Organic idwords 5.5K Referring domains 364 UR 24 DR 2.5',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '9',
  },
  {
    id: 15,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/3b1aab10-e107-4bf3-9a58-757e32b160bd.jpeg',
    category: 'WEBSITE',
    websitename: 'FindBestVacuumForStairs.Com',
    description:
      '140+ Unique Referring Domains|Starter Vaccum Cleaner Niche Review Site|USA Traffic|Wordpress Adsense Amazon Affiliate|104 Blogs.',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '22',
  },
  {
    id: 16,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/fd5cc8e7-f8c8-4373-98c9-cf16ee1b107b.png',
    category: 'Andriod App',
    websitename: 'Russemusikk',
    description:
      'A scientA 7 year old ecommerce business in the entertainment industry earning $5,000 per month. Absolutley no work needed, as 4 Famous producers will do EVERYTHING!!!ific calculator that is easy to use.',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '17',
  },
  {
    id: 17,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/website_regular_a3cbaf61-3366-4161-97a9-8ebf58b22d0f.jpg',
    category: 'DOMAIN',
    websitename: 'tatto.com',
    description:
      '4 y/o eCommerce in the Personalized Tattoo Design Niche Generating a Net Profit of $800 p/mo. Two Domains & 5.8k+ Followers on SM!',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '1',
  },
  {
    id: 18,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/9d7a91d8-4e44-4873-a591-bf92c8067150.png',
    category: 'WEBSITE',
    websitename: 'Print On Canvas',
    description:
      'A 15 Years old business - Run in Singapore | Can run globally | highly profitable Print On Demand Business | No Maintenance Required | Huge Potential',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '12',
  },
  {
    id: 19,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/website_regular_6ca634ed-01ce-4817-af5b-9358d8186216.jpg',
    category: 'PROJECT',
    websitename: 'LawEnforcement.com',
    description:
      'Proprietary SaaS software product with 5 functional websites for Law Enforcement and SMB market.Over 30 top level domains. ID printing equipment and supplies included in the sale.',
    price: '10000 PKR',
    status: 'sign up / Log in first to view',
    bid: '10',
  },
  {
    id: 20,
    img: 'https://d2jafhvbn4akdi.cloudfront.net/91511b81-f627-4ee4-bc26-ed17edca169d.png',
    category: 'WEBSITE',
    websitename: 'Web Completa',
    description:
      'Created in WordPress with the Divi theme. This website integrates a successful online business based on web services, subscriptions, advertising and more.',
    price: '20000 PKR',
    status: 'sign up / Log in first to view',
    bid: '5',
  },
]
